version: '3'
services:

  angular:
    build: angular
    depends_on:
      - nodejs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/prod:/etc/nginx/conf.d
      - ./dhparam:/etc/ssl/certs
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      
  nodejs:
    build: nodejs
# volume needs to be mounted using the following command
# sudo mount -o discard,defaults /dev/sdb ./data
    volumes:
      - ./data/ASTGTMV003:/data
    ports:
      - "8080:8080"

volumes:
    certbot-etc:
    certbot-var:
