version: '3'
services:

  angular:
    build: angular
    depends_on:
      - nodejs
    ports:
      - "80:80"
      - "443:443"
    volumes:
# this is a fix, it maps contents of the static nginx root folder, to a docker container with the
# same path with challenge at the end.  this along with settings in the ./nginx-conf/prod/default.conf
# file allow the acme certbot challenge to work correctly
      - /usr/share/nginx/html:/usr/share/nginx/html/challenge
# this maps the nginx configuration file to the correct location in the container
      - ./nginx:/etc/nginx/conf.d
# this maps the local ssl certificated to the correct location in the container
      - ./dhparam:/etc/ssl/certs
# these named volumes are not working, but dont know why - so redone as bind mounts below
#      - certbot-etc:/etc/letsencrypt
#      - certbot-var:/var/lib/letsencrypt
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      
  nodejs:
    build: nodejs
# volume needs to be mounted using the following command
# sudo mount -o discard,defaults /dev/sdb ./data
    volumes:
      - ./data/ASTGTMV003:/data
    ports:
      - "8080:8080"

# volumes:
#   certbot-etc:
#   certbot-var: