version: '3'
services:
  angular:
    # container_name: angular
    # hostname: angular
    build: angular
    depends_on:
      - nodejs
    ports:
      - "80:80"
  nodejs:
    # container_name: nodejs
    # hostname: nodejs
    build: nodejs
# volume needs to be mounted using the following command
# sudo mount -o discard,defaults /dev/sdb ./data
    volumes:
      - ./data/ASTGTMV003:/data
    ports:
      - "8080:8080"
